install_shop_with_modules:
  cache:
    prepared_shop: false
  composer:
    transform: |
      {
          "require": {
              "oxid-esales/oxideshop-ce": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-admin-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/developer-tools": "{{ .Data.global.composer.dev_ref }}",
              "fresh-advance/nutrition-facts": "dev-{{ .Github.RefName }}"
          },
          "repositories": {
            "fresh-advance/nutrition-facts": {
              "type": "git",
              "url": "https://github.com/Fresh-Advance/NutritionFacts.git"
            }
          }
      }
  custom_script_container: |
    vendor/bin/oe-console oe:database:reset --db-host=mysql --db-port=3306 --db-name=example --db-user=root --db-password=root --force
    vendor/bin/oe-console oe:module:activate fa_nutrition_facts
    vendor/bin/oe-console oe:theme:activate twig

runscript: &runscript
  matrix:
    script: |
      [
        "fa_nutrition_facts:tests-clover",
        "fa_nutrition_facts:tests-codeception",
      ]
  fa_nutrition_facts:
    path: 'vendor/fresh-advance/nutrition-facts'

runslim:
  <<: *runscript
  matrix:
    script: |
      [
        "fa_nutrition_facts:phpstan",
        "fa_nutrition_facts:phpmd",
        "fa_nutrition_facts:phpcs",
      ]

sonarcloud:
  matrix:
    testplan: '["-"]'
  strip_path: '/var/www/vendor/fresh-advance/nutrition-facts/'
  project_name: 'Nutrition Facts'
  project_key: 'Fresh-Advance_NutritionFacts'
  organization: 'fresh-advance'
  parameters: |
    -Dsonar.language=php
    -Dsonar.scm.provider=git
    -Dsonar.sources=src
    -Dsonar.tests=tests
