services:
  _defaults:
    public: false
    autowire: true

  FreshAdvance\NutritionFacts\DataTypeFactory\NutritionFactsFactoryInterface:
    class: FreshAdvance\NutritionFacts\DataTypeFactory\NutritionFactsFactory