services:
  _defaults:
    public: false
    autowire: true

  FreshAdvance\NutritionFacts\DataTypeFactory\NutritionFactsFactoryInterface:
    class: FreshAdvance\NutritionFacts\DataTypeFactory\NutritionFactsFactory

  FreshAdvance\NutritionFacts\DataTypeFactory\ProductFactsFactoryInterface:
    class: FreshAdvance\NutritionFacts\DataTypeFactory\ProductFactsFactory