services:
  _defaults:
    public: false
    autowire: true
    bind:
      Doctrine\DBAL\Connection: '@=service("OxidEsales\\EshopCommunity\\Internal\\Framework\\Database\\ConnectionProviderInterface").get()'

  FreshAdvance\NutritionFacts\Repository\FactsDataAccessInterface:
    class: FreshAdvance\NutritionFacts\Repository\FactsDataAccess

  FreshAdvance\NutritionFacts\Repository\FactsRepositoryInterface:
    class: FreshAdvance\NutritionFacts\Repository\FactsRepository
    arguments:
      FreshAdvance\NutritionFacts\Serializer\FactsSerializerInterface: '@FreshAdvance\NutritionFacts\Serializer\JsonSerializer'

  FreshAdvance\NutritionFacts\Serializer\JsonSerializer: ~
  FreshAdvance\NutritionFacts\Serializer\YamlSerializer: ~
